// <auto-generated />
using System;
using Avalanche.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avalanche.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250620020525_AddingUniqueIndex")]
    partial class AddingUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Affiliate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("AffiliateDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Affiliates", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.AffiliatePolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("AffiliationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DesAffiliationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("StatusId");

                    b.ToTable("AffiliatePolicies", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Authorization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ApplicationAmount")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<double?>("ApprovedAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("AuthorizationTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HospitalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateId");

                    b.HasIndex("AuthorizationTypeId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("StatusId");

                    b.ToTable("Authorizations", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.AuthorizationType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthorizationTypes", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CustomerSince")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Coverage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coverages", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.DocumentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Hospital", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstitutionTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Hospitals", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.InstitutionType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InstitutionTypes", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("MonthlyCost")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.PlanCoverage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("AmountLimit")
                        .HasColumnType("double precision");

                    b.Property<string>("CoverageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CoveragePercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearFrequencyLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanCoverages", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Policy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EffectiveEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("StatusId");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Status", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses", (string)null);
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Affiliate", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.Client", "Client")
                        .WithMany("Affiliates")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany("Affiliates")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Status", "Status")
                        .WithMany("Affiliates")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DocumentType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.AffiliatePolicy", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.Affiliate", "Affiliate")
                        .WithMany("AffiliatePolicies")
                        .HasForeignKey("AffiliateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Policy", "Policy")
                        .WithMany("AffiliatePolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Status", "Status")
                        .WithMany("AffiliatePolicies")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliate");

                    b.Navigation("Policy");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Authorization", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.Affiliate", "Affiliate")
                        .WithMany("Authorizations")
                        .HasForeignKey("AffiliateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.AuthorizationType", "AuthorizationType")
                        .WithMany("Authorizations")
                        .HasForeignKey("AuthorizationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Authorizations")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Policy", "Policy")
                        .WithMany("Authorizations")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Status", "Status")
                        .WithMany("Authorizations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliate");

                    b.Navigation("AuthorizationType");

                    b.Navigation("Hospital");

                    b.Navigation("Policy");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Client", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany("Clients")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Status", "Status")
                        .WithMany("Clients")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Hospital", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.InstitutionType", "InstitutionType")
                        .WithMany("Hospitals")
                        .HasForeignKey("InstitutionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Status", "Status")
                        .WithMany("Hospitals")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstitutionType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.PlanCoverage", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.Coverage", "Coverage")
                        .WithMany("PlanCoverages")
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanCoverages")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coverage");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Policy", b =>
                {
                    b.HasOne("Avalanche.Core.Domain.Entities.Client", "Client")
                        .WithMany("Policies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Plan", "Plan")
                        .WithMany("Policies")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalanche.Core.Domain.Entities.Status", "Status")
                        .WithMany("Policies")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Plan");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Affiliate", b =>
                {
                    b.Navigation("AffiliatePolicies");

                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.AuthorizationType", b =>
                {
                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Client", b =>
                {
                    b.Navigation("Affiliates");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Coverage", b =>
                {
                    b.Navigation("PlanCoverages");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.DocumentType", b =>
                {
                    b.Navigation("Affiliates");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Hospital", b =>
                {
                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.InstitutionType", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanCoverages");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Policy", b =>
                {
                    b.Navigation("AffiliatePolicies");

                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("Avalanche.Core.Domain.Entities.Status", b =>
                {
                    b.Navigation("AffiliatePolicies");

                    b.Navigation("Affiliates");

                    b.Navigation("Authorizations");

                    b.Navigation("Clients");

                    b.Navigation("Hospitals");

                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
